---

- name: Install keeweb packages
  pacman:
    name: '{{ q("flattened", (keeweb__packages +
                              keeweb__dependent_packages)) }}'
    state: 'present'
  register: keeweb__register_pacman
  until: keeweb__register_pacman is succeeded

- name: Install keeweb AUR packages
  aur:
    name: '{{ keeweb__aur_packages }}'
    state: 'present'
  register: keeweb__register_aur
  until: keeweb__register_aur is succeeded
  become: False

- name: Add pam sddm auth rule for gnome keyring
  pamd:
    name: 'sddm'
    type: 'auth'
    control: 'optional'
    module_path: 'pam_kwallet5.so'
    new_type: 'auth'
    new_control: 'optional'
    new_module_path: 'pam_gnome_keyring.so'
    state: 'after'

- name: Add pam sddm session rule for gnome keyring
  pamd:
    name: 'sddm'
    type: 'session'
    control: 'optional'
    module_path: 'pam_kwallet5.so'
    new_type: 'session'
    new_control: 'optional'
    new_module_path: 'pam_gnome_keyring.so'
    module_arguments: 'auto_start'
    state: 'after'
