---

- name: Install pulseaudio packages
  pacman:
    name: '{{ q("flattened", (pulseaudio__packages +
                              pulseaudio__dependent_packages)) }}'
    state: 'present'
  register: pulseaudio__register_pacman
  until: pulseaudio__register_pacman is succeeded

- name: Get alsa pci input source name
  shell: |
    set -o pipefail
    pactl list short sources | gawk '/alsa_input\.pci/ { print $2 }'
  args:
    executable: '/bin/bash'
  register: pulseaudio__register_pactl
  changed_when: False
  check_mode: False
  become: False

- name: Set fact about loopback source
  set_fact:
    pulseaudio__loopback_source:
      '{{ pulseaudio__register_pactl.stdout_lines[0] }}'

- name: Install default configuration file
  template:
    src: 'default.pa.j2'
    dest: '~/.config/pulse/default.pa'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'
  become: False
