---

- name: Install dotfiles packages
  pacman:
    name: '{{ q("flattened", (dotfiles__packages +
                              dotfiles__dependent_packages)) }}'
    state: 'present'
  register: dotfiles__register_pacman
  until: dotfiles__register_pacman is succeeded

- name: Checkout git repo
  git:
    repo: '{{ dotfiles__repo }}'
    dest: '{{ dotfiles__dest_path }}'
    version: 'master'
  register: dotfiles__register_git
  until: dotfiles__register_git is succeeded
  become: False

- name: Install user configuration files
  make:
    chdir: '{{ dotfiles__dest_path }}'
    target: 'install'
  become: False
