---

- name: Include OS-specific variables
  include_vars: '{{ lookup("first_found", params) }}'
  vars:
    params:
      files:
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
      paths:
        - 'vars'

- name: Include user tasks
  include_tasks: 'user.yml'
  when: common_user_enabled|bool

- name: Include containerization tasks
  include_tasks: 'containerization.yml'
  when: common_containerization_enabled|bool

- name: Include desktop tasks
  include_tasks: 'desktop.yml'
  when: common_desktop_enabled|bool

- name: Include development tasks
  include_tasks: 'development.yml'
  when: common_development_enabled|bool
