---

- name: Install sddm packages
  pacman:
    name: '{{ q("flattened", (sddm__packages + sddm__dependent_packages)) }}'
    state: 'present'
  register: sddm__register_pacman
  until: sddm__register_pacman is succeeded

- name: Ensure "Numlock=on" is set in section "[General]" in configuration file
  ini_file:
    path: '/etc/sddm.conf'
    section: 'General'
    option: 'Numlock'
    value: 'on'
    no_extra_spaces: True
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Update Xorg startup script
  blockinfile:
    path: '/usr/share/sddm/scripts/Xsetup'
    block: '{{ lookup("file", "xrandr-setup") }}'
