---

- name: Install nvidia packages
  pacman:
    name: '{{ q("flattened", (nvidia__packages +
                              nvidia__dependent_packages)) }}'
    state: 'present'
  register: nvidia__register_pacman
  until: nvidia__register_pacman is succeeded

- name: Install kernel module configuration file
  template:
    src: 'nvidia-module.conf.j2'
    dest: '/etc/modprobe.d/nvidia.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Get gp108 busid
  shell: |
    set -o pipefail
    lspci -Dnnmm | gawk -v FPAT='([^ ]+)|("[^"]+")' '
    $2 ~ /VGA/ && $3 ~ /NVIDIA/ && $4 ~ /GP108/ {
      patsplit($1, arr, /[^:.]+/)
      for (i in arr)
        arr[i] = strtonum("0x" arr[i])
      print arr[2] (arr[1] == 0 ? "" : "@" arr[1]) ":" arr[3] ":" arr[4]
    }
    '
  args:
    executable: '/bin/bash'
  register: nvidia__register_lspci
  changed_when: False
  check_mode: False

- name: Set fact about gp108 busid
  set_fact:
    nvidia__gp108_busid: '{{ nvidia__register_lspci.stdout_lines[0] }}'

- name: Install Xorg configuration file
  template:
    src: 'nvidia-xorg.conf.j2'
    dest: '/etc/X11/mhwd.d/nvidia.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
