---

- name: Install libvirt packages
  pacman:
    name: '{{ q("flattened", (libvirt__packages +
                              libvirt__dependent_packages)) }}'
    state: 'present'
  register: libvirt__register_pacman
  until: libvirt__register_pacman is succeeded
  notify: ['Restart service']

- name: Add user to virtualization group
  user:
    name: '{{ ansible_user }}'
    groups: 'libvirt'
    append: True
  notify: ['Restart service']

- name: Install hooks
  synchronize:
    src: 'hooks/'
    dest: '/etc/libvirt/hooks'
    delete: True
    copy_links: True
  notify: ['Restart service']
