---

- name: Install initramfs packages
  pacman:
    name: '{{ q("flattened", (initramfs__packages +
                              initramfs__dependent_packages)) }}'
    state: 'present'
  register: initramfs__register_pacman
  until: initramfs__register_pacman is succeeded

- name: Get running kernel name
  shell: |
    set -o pipefail
    mhwd-kernel -li | gawk 'NR == 1 { print gensub(/[()]/, "", "g", $4) }'
  args:
    executable: '/bin/bash'
  register: initramfs__register_mhwd
  changed_when: False
  check_mode: False

- name: Set fact about mkinitcpio preset
  set_fact:
    initramfs__preset: '{{ initramfs__register_mhwd.stdout_lines[0] }}'

- name: Update additional modules
  lineinfile:
    path: '/etc/mkinitcpio.conf'
    regexp: '^MODULES='
    line: 'MODULES=({{ initramfs__modules | join(" ") }})'
  notify: ['Generate initial ramdisk environment']
