---

- name: Install mhwd packages
  pacman:
    name: '{{ q("flattened", (mhwd__packages + mhwd__dependent_packages)) }}'
    state: 'present'
  register: mhwd__register_pacman
  until: mhwd__register_pacman is succeeded

- name: Get installed video drivers
  shell: |
    set -o pipefail
    mhwd -li | gawk 'NR > 4 && /^ / { print $1 }'
  args:
    executable: '/bin/bash'
  register: mhwd__register_mhwd_li
  changed_when: False
  check_mode: False

- name: Set facts about video drivers
  set_fact:
    mhwd__extra_video_drivers:
      '{{ mhwd__register_mhwd_li.stdout_lines
          | difference(mhwd__video_drivers) }}'
    mhwd__missing_video_drivers:
      '{{ mhwd__video_drivers
          | difference(mhwd__register_mhwd_li.stdout_lines) }}'

- name: Remove extra video drivers
  command: mhwd -r pci '{{ item }}'
  loop: '{{ mhwd__extra_video_drivers }}'

- name: Install missing video drivers
  command: mhwd -i pci '{{ item }}'
  loop: '{{ mhwd__missing_video_drivers }}'
  register: mhwd__register_mhwd_i
  until: mhwd__register_mhwd_i is succeeded
