---

- name: Install java packages
  pacman:
    name: '{{ q("flattened", (java__packages + java__dependent_packages)) }}'
    state: 'present'
  register: java__register_pacman
  until: java__register_pacman is succeeded

- name: Get default environment
  command: archlinux-java get
  register: java__register_java_helper
  changed_when: java__default_env != java__register_java_helper.stdout_lines[0]
  notify: ['Update default environment']
  check_mode: False
