---

- name: Install containers packages
  pacman:
    name: '{{ q("flattened", (containers__packages +
                              containers__dependent_packages)) }}'
    state: 'present'
  register: containers__register_pacman
  until: containers__register_pacman is succeeded

- name: Install subuid configuration file
  template:
    src: 'subu+gid.j2'
    dest: '/etc/subuid'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: ['Migrate containers']

- name: Install subgid configuration file
  template:
    src: 'subu+gid.j2'
    dest: '/etc/subgid'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: ['Migrate containers']
