---

- name: Install synology packages
  pacman:
    name: '{{ q("flattened", (synology__packages +
                              synology__dependent_packages)) }}'
    state: 'present'
  register: synology__register_pacman
  until: synology__register_pacman is succeeded

- name: Update system ssh known hosts
  known_hosts:
    path: '/etc/ssh/ssh_known_hosts'
    name: '{{ synology__nas_host }}'
    key: '{{ lookup("pipe", "ssh-keyscan " + synology__nas_host) }}'
    state: 'present'

- name: Ensure nas is mounted
  mount:
    path: '{{ synology__nas_mountpoint }}'
    src: '{{ ansible_user }}@{{ synology__nas_host }}:/'
    fstype: 'fuse.sshfs'
    opts: 'noauto,x-systemd.automount,_netdev,users,idmap=user,IdentityFile={{ synology__nas_identity_file }},allow_other,reconnect'
    state: 'mounted'

- name: Update dolphin user-places configuration
  blockinfile:
    path: '~/.local/share/user-places.xbel'
    block: '{{ lookup("template", "dolphin-user-places.xbel.j2") }}'
    marker: '<!-- {mark} ANSIBLE MANAGED BLOCK -->'
    insertbefore: '</xbel>'
  become: False

- name: Ensure CloudSyncDecryptionTool install directory exists
  file:
    path: '/opt/Synology/CloudSyncDecryptionTool'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Install CloudSyncDecryptionTool
  unarchive:
    src: '{{ synology__cloud_sync_decryption_tool_download_url }}'
    dest: '/opt/Synology/CloudSyncDecryptionTool'
    remote_src: True
    owner: 'root'
    group: 'root'
    mode: '0755'
