---

- name: Add VSCode PPA on Debian based systems
  block:
    - name: Add Microsoft signing key
      apt_key:
        url: 'https://packages.microsoft.com/keys/microsoft.asc'
        state: 'present'
    - name: Add VSCode repository into sources list
      apt_repository:
        repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
        state: 'present'
  when: ansible_facts["os_family"] == "Debian"
  become: True

- name: Install devel packages
  package:
    name: '{{ common_devel__packages }}'
    state: 'present'
  register: common_devel__register_packages
  until: common_devel__register_packages is succeeded
  become: True

- name: Install pre-commit framework
  shell: |
    set -o pipefail
    curl 'https://pre-commit.com/install-local.py' | python -
  args:
    creates: '~/bin/pre-commit'
    executable: '/bin/bash'

- name: Download cheat.sh command line client
  get_url:
    url: 'https://cht.sh/:cht.sh'
    dest: '~/bin/cht.sh'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Download cheat.sh Zsh completions
  get_url:
    url: 'https://cht.sh/:zsh'
    dest: '~/.zsh.d/_cht'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'
  when: common_user_enabled|bool

- name: Perform C language tasks
  block:
    - name: Install C language packages
      package:
        name: '{{ common_devel_c__packages }}'
        state: 'present'
      register: common_devel_c__register_packages
      until: common_devel_c__register_packages is succeeded
      become: True
  when: common_devel_c_enabled|bool

- name: Perform Go language tasks
  block:
    - name: Install Go language packages
      package:
        name: '{{ common_devel_go__packages }}'
        state: 'present'
      register: common_devel_go__register_packages
      until: common_devel_go__register_packages is succeeded
      become: True
  when: common_devel_go_enabled|bool

- name: Perform Java language tasks
  block:
    - name: Install Java language packages
      package:
        name: '{{ common_devel_java__packages }}'
        state: 'present'
      register: common_devel_java__register_packages
      until: common_devel_java__register_packages is succeeded
      become: True
    - name: Update default Java environment on Archlinux based systems
      block:
        - name: Get default Java environment
          command: archlinux-java get
          register: common_devel_java__register_archlinux_java
          changed_when: False
          check_mode: False
        - name: Set default Java environment
          command: archlinux-java set {{ common_devel_java__environ }}
          vars:
            common_devel_java__default_environ:
              '{{ common_devel_java__register_archlinux_java.stdout | trim }}'
          when: common_devel_java__default_environ != common_devel_java__environ
          become: True
      when: ansible_facts["os_family"] == "Archlinux"
  when: common_devel_java_enabled|bool
