---

- name: Include OS-specific variables
  include_vars: '{{ lookup("first_found", params) }}'
  vars:
    params:
      files:
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
      paths:
        - 'vars'

- name: Include user tasks
  include_tasks: 'user.yml'
  when: common_user_enabled|bool

- name: Include desktop tasks
  include_tasks: 'desktop.yml'
  when: common_desktop_enabled|bool

- name: Include devel tasks
  include_tasks: 'devel.yml'
  when: common_devel_enabled|bool

- name: Include Docker tasks
  include_tasks: 'docker.yml'
  when: common_docker_enabled|bool
