---

- name: Install vfio packages
  pacman:
    name: '{{ q("flattened", (vfio__packages + vfio__dependent_packages)) }}'
    state: 'present'
  register: vfio__register_pacman
  until: vfio__register_pacman is succeeded

- name: Get pci passthrough device ids
  shell: |
    set -o pipefail
    lspci -Dnnmm | gawk -v FPAT='([^ ]+)|("[^"]+")' '
    ($2 ~ /USB/ && $3 ~ /Renesas/ && $4 ~ /uPD720202/) ||
    ($2 ~ /VGA|Audio/ && $3 ~ /NVIDIA/ && $4 ~ /GP104/) {
      print substr($3, length($3) - 5, 4) ":" substr($4, length($4) - 5, 4)
    }
    '
  args:
    executable: '/bin/bash'
  register: vfio__register_lspci
  changed_when: False
  check_mode: False

- name: Set fact about pci passthrough device ids
  set_fact:
    vfio__pci_device_ids: '{{ vfio__register_lspci.stdout_lines | join(",") }}'

- name: Install kernel module configuration file
  template:
    src: 'vfio-module.conf.j2'
    dest: '/etc/modprobe.d/vfio.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
